### PR TITLE
feat: add e-lab testimonials

### PR DESCRIPTION
**Pull request by timonschramm**
Hi there, 
this website should be used starting on 01.08. 
The Links for the application are currently pointing to unfinished Tallyforms, but they will be finished before the 01.08.
Please also change the Link in the navbar to the correct site then. 

Thank you so much.

P.S The navbar looks still odd on phones

### CODE REVIEW

**Comment by simon-hng** [comment]
Overall looks good. 

- you can change the link in the navigation in this pr as well
- can you attach screenshots and explain the problem with the nav in more detail?
- we'll open a pr after this is merged for your public deployment 


Here are some remaining points:

You're still failing some checks:
- prettier: run yarn format
- pr title does not conform to conventional commits


I think the hero text looked better with left align. Any other opinions on that? @Max-vS @MunzerDw 

The testimonials look nice and work really well

**Comment by Max-vS** [comment]
The size of Florian Scherls picture in the Testimonials is not a perfect circle, causing some arrangement issues. 
I would agree to Simon: Hero looks better when left aligned.
Overall nice work!

**Comment by timonschramm** [comment]
IMG_9007

this is the problem with the navbar on mobile

**Comment by Max-vS** [comment]
I think the issue with the Header on mobile, can be resolved by adding a margin to the top, when a certain media width is reached. Can be easily done with Tailwinds responsive features.

**Comment by simon-hng** [comment]
It's not really an issue with margins but instead that this navigation was never intended to have 7 top level links.

For smaller screens like that we need some overflow scrolling

**Comment by timonschramm** [comment]
> * pr title does not conform to conventional commits

But when the PR Title passes it should be fine, shouldn't it?

**Comment by timonschramm** [comment]
I also cropped the photo from florian

**Comment by timonschramm** [comment]
I also added a video instead of the photo

**Review by simon-hng — APPROVED** [review]

**Pull request merged**
